#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch 2: artikel 6-10"""
from gen_articles import build

build("cara-menghilangkan-bau-dari-wc", 4, [
"<strong>Bau menyengat dari WC hampir selalu berasal dari tiga sumber: seal kloset yang bocor, bak kontrol yang jenuh lumpur, atau pipa ventilasi tangki yang tersumbat.</strong> Pewangi ruangan dan karbol hanya menimbun bau dengan wewangian selama beberapa jam — sumber gas sulfida tetap mengeluarkan pasokannya. Cara yang benar adalah urutan pengecekan enam titik dari yang termurah sampai yang butuh teknisi; sebagian besar kasus selesai di dua titik pertama.",
"Bau juga bukan satu jenis: ada yang anyir seperti got, ada yang manis kimia, ada yang telur busuk tajam. Masing-masing menunjuk sumber berbeda. Artikel ini mengajarkan mencocokkan karakter bau dengan titik asalnya, plus langkah cepat meredakannya malam ini sebelum perbaikan tuntas dilakukan besok.",
"<h2>Kenali Dulu Jenis Baunya</h2>",
"Bau telur busuk (sulfida) khas dari tangki/resapan — gas hasil penguraian anaerob. Bau anyir got biasanya air trap kering: lengkung pipa di bawah wastafel atau shower yang kehilangan genangan airnya sehingga gas bebas naik. Bau pesing amoniak menandakan rembesan urine di nat keramik atau lantai area basah yang tidak dibersihkan sampai kedalaman nat. Dan bau manis samar dekat tutup tangki bisa berarti kebocoran lidah penutup beton yang retak.",
"@@                <div class=\"info-box\">\n                    <strong>Tes cepat air trap</strong>\n                    Tuang 1 liter air ke setiap floor drain dan saluran shower yang jarang dipakai. Kalau bau berkurang dalam semalam, masalahnya hanya water seal yang mengering — rutinitas sebulan sekali menyelesaikan selamanya. Ini penyebab paling sering di kamar mandi kedua rumah yang jarang digunakan.\n                </div>",
"<h2>Titik #1: Seal dan Dudukan Kloset</h2>",
"Cium permukaan lantai di pangkal kloset saat disiram. Bau keluar dari celah itu = segel/wax ring atau sambungan klep pembuangan di belakang kloset bocor. Gas dari jalur pembuangan menyelinap lewat rongga kecil di bawah keramik. Perbaikannya murah: lepas kloset, ganti segel baru, rapatkan sambungan, pasang kembali. Bisa dikerjakan sendiri kalau Anda nyaman membongkar keramik, atau menitipkan pada teknisi sedot WC sekalian kunjungan rutin.",
"Varian Medan klasik: kloset duduk dipasang di atas lantai yang sering dipel basah. Air pel masuk ke celah dudukan, membasahi lapisan kotoran tahunan di bawahnya, dan menghasilkan bau lembap campur got yang dikira \"dari tangki\" padahal tidak pernah sampai ke luar rumah.",
"<h2>Titik #2–4: Bak Kontrol, Ventilasi, Tangki</h2>",
"Buka bak kontrol: permukaan air tinggi dan endapan gelap berbau tajam berarti sistem sudah penuh sampai hilir — penyedotan diperlukan, bukan deodoran. Lalu lihat pipa ventilasi atap: ujung terbuka tanpa tutung kawat mudah dihuni sarang laba-laba dan daun, membuat gas balik arah mencari jalan keluar lain — biasanya lewat kloset. Cek terakhir: tutup tangki. Retak rambut di beton penutup cukup lebar melepas gas tiap tekanan internal naik.",
"Kalau bau menguat setelah hujan deras, curigai resapan jenuh: air hujan tidak punya tempat menyerap dan mendorong gas naik lewat jalur septik. Pola musiman ini dibahas terpisah di artikel musim hujan dan septic tank.",
"<h2>Titik #5–6: Got Luar dan Halaman</h2>",
"Talangnya sering di luar rumah: selokan lingkungan mampet membuat bau got \"bermigrasi\" ke halaman dan kamar mandi lewat celah-celah. Amati apakah bau juga muncul di depan rumah, bukan hanya dalam. Kalau ya, perbaiki aliran got lingkungan lebih dulu — kerja bakti satu meter selokan mengalahkan seluruh produk pengharup di rak supermarket.",
"Genangan air limbah halus di taman (sering tak terlihat karena merembes) menghasilkan bau tanah basah busuk persisten. Tes sederhana: tancapkan kayu kecil di area yang dicurigai; bila keluar cairan keruh berbau, jalur rembesan sudah mendekati permukaan dan tangki perlu diperiksa volumenya minggu itu.",
"<h2>Urutan Bertindak Malam Ini</h2>",
"Satu: tuang air ke semua drain kering. Dua: bersihkan nat dan lantai sekitar pangkal kloset sampai kedalaman nat dengan sikat. Tiga: cium bak kontrol (pakai masker, jangan condongkan wajah). Empat: cek ujung ventilasi atap. Bila empat langkah tidak mengubah apa pun, kemungkinan besar sumbernya volume tangki atau resapan — dua hal yang memang ranah alat sedot, bukan alat bersih-bersih. Kirim video bau-ke mana-paling-terasa lewat WhatsApp, kami bantu arahkan diagnosis awalnya gratis.",
], [
("Kenapa bau muncul hanya pagi hari?", "Malam tanpa pemakaian memberi waktu gas terakumulasi di rongka pipa; siraman pertama pagi menyodorkannya ke ruang. Sering tanda seal kloset bocor atau ventilasi kurang tarik."),
("Kapur barus dan kopi efektif?", "Menyamarkan sementara, tidak menetralkan sulfida. Jangan jadikan solusi utama — bau yang tertutup adalah bau yang terus diproduksi."),
("Bau dari shower jarang dipakai, normal?", "Tidak, tapi mudah: water seal-nya kering. Alirkan air 1 liter tiap dua minggu untuk semua drain yang jarang dipakai agar lengkung pipa tetap berisi penutup gas."),
("Berapa lama bau hilang setelah tangki disedot?", "Bau sumbernya langsung turun drastis begitu lumpur diangkat. Sisa bau di tanah/area yang sempat tergenang butuh 1–2 minggu ventilasi alami atau penyemprotan disinfektan lokasi."),
])

build("alat-sederhana-wc-mampet", 4, [
"<strong>Empat alat rumahan yang efektif mengatasi WC mampet: plunger karet, kawat spiral (drain snake), campuran soda kue–cuka, dan pompa tangan pressurizer — masing-masing punya medan tugas berbeda.</strong> Plunger untuk sumbatan lunak dekat kloset, spiral untuk benda yang tersangkut di sifon, soda kue–cuka untuk lendir ringan di pipa, pompa pressur untuk dorongan air keras. Salah alat sama dengan memperpanjang mampet dan kadang merusak pipa.",
"Panduan ini mengurutkan dari yang paling aman, menjelaskan teknik pakai yang benar (mayoritas kegagalan terjadi karena teknik, bukan alatnya), dan memberi batas tegas kapan berhenti mencoba sendiri. Prinsip besarnya: dua percobaan gagal = panggil bantuan profesional, sebelum biaya mandiri berubah jadi biaya bongkar.",
"<h2>Plunger: Teknik yang Benar</h2>",
"Pilih plunger mangkuk (cup) dengan bibir flange untuk kloset, bukan plunger wastafel datar. Isi mangkuk kloset secukupnya agar bibir karet terendam — udara lebih mudah dimampatkan daripada air, dan itulah penyebab \"cokek-cokek tanpa hasil\". Tekan perlahan untuk membuang udara, lalu tarik-tekan mantap 15–20 kali tanpa memecah segel karet di permukaan. Akhiri dengan tarikan kuat: sumbatan kertas sering lepas justru saat tekanan negatif.",
"Jangan menyiram di tengah proses — air tambahan menaikkan ketinggian rawan luber. Setelah berhasil, alirkan air bersih satu ember penuh untuk memastikan jalur benar-benar lapang, bukan sekadar bolongan kecil di tengah sumbatan.",
"<h2>Kawat Spiral dan Kait Darurat</h2>",
"Spiral pendek 1,5–3 meter dijual murah di toko bangunan. Masukkan perlahan sambil diputar sampai terasa hambatan, lalu tarik-naikkan berulang untuk menggigit sumbatan. Untuk benda licin (botol, mainan), gantungkan kait dari hanger kawat yang ujungnya ditekuk seperti mata pancing. Aturan besi: jangan mendorong. Mendorong benda keras ke sifon mengubah pekerjaan 15 menit menjadi bongkar-kloset.",
"@@                <div class=\"info-box warn\">\n                    <strong>Dua hal yang dilarang</strong>\n                    1) Soda api/caustic: panas eksotermiknya meretakkan keramik, melunakkan sambungan PVC, dan membunuh bakteri tangki. 2) Mesin pressure washer tanpa nozzle khusus saluran: menyemburkan air balik ke wajah operator dan mendorong sumbatan makin dalam. Keduanya penyebab nomor satu kerusakan \"korban DIY\".\n                </div>",
"<h2>Soda Kue–Cuka dan Air Panas (Sumur)</h2>",
"Untuk lendir organik ringan dan bau: tuang setengah gelas soda kue, disusul setengah gelas cuka, tutup kloset 20 menit agar reaksi bekerja ke bawah, lalu siram satu panci air panas — bukan mendidih, suhu rebusan bisa meregangkan sambungan dan meretakkan porselen. Efektif untuk perawatan bulanan dan sumbatan tipis; tidak akan menembus gumpalan tisu padat apalagi benda asing.",
"Versi perawatannya: tuang satu ember air panas setiap kali habis mandi sebagai pembilas lemak sabun di pipa shower. Kebiasaan lima detik ini menekan kebutuhan dongkrak pipa tahunan di banyak rumah.",
"<h2>Pompa Tangan Pressurizer</h2>",
"Alat presur manual (tipe toilet blow gun / hand pump saluran) memberi dorongan air terkonsentrasi yang lebih kuat dari siraman biasa. Isi, pompa sampai tekanan menengah, arahkan nozzle ke lubang kloset, tekan pemicu singkat. Cocok untuk sumbatan lunak yang lolos dari plunger. Batasi 3–4 tembakan; jika tidak bergerak juga, jalurnya pasti tersumbat keras atau terletak jauh di hilir — wilayah kerja mesin spiral listrik teknisi.",
"Peringatan khusus bangunan tua: pipa rabat-era 70-an kadang memakai sambungan semen-asbes getas. Tekanan tinggi bisa membuka sambungan yang masih utuh. Kalau rumah Anda berusia di atas 30 tahun dan belum pernah diganti pipanya, mulai dari plunger saja dan biarkan tekanan jadi urusan teknisi.",
"<h2>Kapan Berhenti dan Menelepon</h2>",
"Tanda Anda harus berhenti: air naik sampai ambang luber saat percobaan, bau sulfida ikut muncul, floor drain lain mulai berbuih, atau dua siklus alat gagal total. Keempatnya menandakan masalah di luar jangkauan alat rumahan — umumnya di bak kontrol, tangki, atau kemiringan pipa. Menelepon jasa sedot WC pada titik ini justru menghemat: pekerjaan lokal selesai satu kunjungan sebelum berubah jadi proyek resapan.",
], [
("Plunger tidak boleh dipakai untuk apa?", "Untuk sumbatan benda keras jauh di sifon dan untuk kloset yang terhubung langsung ke tangki penuh — tekanan balik hanya memindahkan gas bau ke ruang. Pastikan dulu gejalanya sumbatan lokal."),
("Enzim/penggura cair bagus tidak?", "Aman untuk pemeliharaan dan lendir organik tipis, tapi lambat (berjam-jam sampai harian) dan tidak menembus sumbatan padat. Jangan bandingkan hasilnya dengan tenaga mekanis."),
("Beli spiral listrik rumahan?", "Untuk satu rumah, spiral manual 3 m cukup. Mesin listrik bayar dirinya hanya kalau Anda melayani banyak titik — sisanya risiko merusak pipa yang belum tentu salah tempat."),
("WC mampet total, air tidak surut sedikit pun — masih bisa DIY?", "Selama belum luber, coba kait kawat untuk kemungkinan benda asing dan plunger 20 tarikan. Tidak berhasil? Hentikan. Sumbat total menandakan jalur penuh — menunggu lebih lama membuat crew bekerja di genangan dan menambah durasi kerja."),
])

build("kesalahan-sehari-hari-septic-tank", 5, [
"<strong>Septic tank cepat penuh bukan karena nasib buruk, melainkan tujuh kebiasaan harian: membuang tisu basah, menuang minyak goreng, mengecat/menyimpan bahan kimia di kloset, memakai pembasmi kuman berlebihan, menyambungkan mesin cuci ke tangki, menunda sedot bertahun-tahun, dan membangun resapan seadanya.</strong> Enam dari tujuh kebiasaan itu gratis dihentikan hari ini; satu sisanya (resapan) diperbaiki sebelum musim hujan berikutnya.",
"Artikel ini membedah mekanisme kerusakan tiap kebiasaan — kenapa bakteri pengurai mati, kenapa lemak menutup baffles, kenapa \"sedikit saja\" menumpuk jadi satu ritase. Setelah paham mekanismenya, mengubah kebiasaan terasa jauh lebih mudah daripada sekadar menghafal daftar larangan.",
"<h2>#1–2: Tisu Basah dan Minyak Goreng</h2>",
"Tisu basah dirancang tidak hancur di air — itulah fitur jualnya — dan ia masuk daftar panjang penyebab sumbatan sifon di seluruh dunia. Satu helai per hari = ratusan helai per tahun mengendap utuh di tangki. Ganti dengan tisu toilet cepat-urai dan tempat sampah bertutup di samping kloset; biaya Rp20 ribu sebulan menyelamatkan jutaan rupiah pekerjaan darurat.",
"Minyak goreng bekas membentuk lapisan mengapung yang menebal setiap dituang. Kerak itu menutupi permukaan tangki, memerangkap gas, menyumbat baffles outlet, dan membungkus padatan sehingga tidak terurai. Tuang sisa minyak ke wadah, bekukan di freezer, buang ke sampah organik — atau kumpulkan untuk bank minyak jelantah yang kini banyak beroperasi di Medan.",
"<h2>#3–4: Bahan Kimia dan Pembasmi Kuman</h2>",
"Soda api, thinner, cat sisa, pestisida rumah tangga, hingga antibiotik limbahan manusia semuanya menyerang populasi bakteri anaerob yang menjadi \"mesin\" tangki. Tangki sehat bergantung koloni mikroba; membunuhnya berarti menghentikan penyusutan lumpur — volume naik lebih cepat, bau meningkat, dan sedot datang lebih dini. Simpan bahan B3 kecil di botol tertutup dan buang lewat layanan sampah berbahaya kelurahan, bukan lewat kloset.",
"Deterjen antibakterial berlebihan untuk cucian harian memberi efek serupa secara diam-diam. Cukup takaran label, dan pilih formula ramah septic bila mesin cuci Anda tersambung ke tangki.",
"<h2>#5–6: Mesin Cuci dan Penundaan Sedot</h2>",
"Satu siklus mesin cuci = 60–100 liter air mendadak masuk tangki, membawa serat deterjen dan lemak sabun. Beban hidraulik kilat itu mendorong endapan keluar menuju resapan — awal mula biomat yang mematikan daya serap. Solusi murah: perpanjang jalur drainase mesin cuci lewat bak penampung kecil, atau jadwalkan cucian di jam rumah sepi, dan idealnya pisahkan saluran greywater dari tangki septik.",
"Penundaan sedot punya efek bola salju: lumpur memadat, mengikat pasir, dan suatu hari tidak bisa lagi diisap selang — harus dipecah manual. Volume yang \"dihemat\" hari ini kembali sebagai biaya tenaga ekstra ditambah potensi resapan rusak. Jadwalkan berdasarkan angka kapasitas, bukan berdasarkan kapan bau mulai tak tertahankan.",
"@@                <div class=\"info-box\">\n                    <strong>Daftar cek mingguan 2 menit</strong>\n                    1) Tempat sampah kecil tersedia di dekat kloset? 2) Ada wadah minyak jelantah di dapur? 3) Lantai sekitar kloset kering dari rembes? 4) Drain jarang dipakai dialiri air? 5) Kalender punya pengingat tanggal sedot terakhir? Lima centang hijau = tangki Anda awet lebih lama dari tetangga.\n                </div>",
"<h2>#7: Resapan Seadanya</h2>",
"Resapan dangkal 1×1 meter dengan isian bata sisa adalah resep genangan musiman. Luas resapan harus sebanding volume tangki dan daya serap tanah lempung setempat. Kalau halaman sering becek di area resapan meski tangki baru disedot, masalahnya struktural — konsultasikan pembuatan sumur resapan dalam atau bidang resapan berpori sebelum November tiba.",
"Merawat septic tank pada dasarnya adalah merawat bakteri dan menjaga air bersih tidak masuk ke jalur kotor. Dua prinsip itu menutup tujuh kebiasaan perusak di atas. Dan ketika jadwal sedot tiba, gunakan penyedia yang mencatat volume terangkat — data itu adalah rapor kesehatan tangki Anda dari tahun ke tahun.",
], [
("Pengharum cair gantung di bak mandi aman?", "Umumnya aman dalam jumlah wajar; kandungan utamanya surfaktan dan pewangi encer. Yang merusak adalah varian \"pembersih kuat otomatis\" berkadar disinfektan tinggi."),
("Apa pengganti soda api untuk WC berkerak?", "Asam sitrat/air jeruk nipis pekat + sikat pegangan panjang. Kerak mineral memang sulit, tapi tidak sepadan risikonya dibanding caustic yang membakar pipa dan kulit."),
("Greywater (cucian) boleh digabung ke septik?", "Sebaiknya tidak untuk mesin cuci. Mandi/wastafel volume kecil masih tolerable. Pisahkan jalur greywater ke resapan tersendiri bila renovasi memungkinkan."),
("Bagaimana tahu bakteri tangki saya \"mati\"?", "Tandanya: sedot terlalu sering padahal pemakaian normal, bau sulfida ekstrem, dan lumpur terangkat tampak segar tak terurai (serat terlihat utuh). Pemulihan: hentikan input kimia, tambahkan starter enzim, patuhi jadwal."),
])

build("resapan-air-macet-penanganan", 4, [
"<strong>Resapan macet ditandai air yang menggenang lebih dari beberapa jam setelah pemakaian berat, dan penyebabnya berlapis: sumbatan biomat di dinding tanah, tanah liat asli yang porositasnya rendah, akar pohon menyumbat pori, atau dimensi resapan yang sejak awal kurang luas.</strong> Kabar baiknya, tiga tingkat penanganan tersedia dari yang termurah (istirahatkan dan sanggah) sampai menyeluruh (sumur resapan baru) — dan urutan memilihnya ditentukan umur serta pola genangan.",
"Di Medan, resapan sering luput dari perhatian sampai musim hujan membuktikan kelemahannya. Padahal resapan adalah \"paruh kedua\" sistem septik: tangki mengurai, resapan menampung limpahan cairan. Ketika resapan mati, gejala yang terasa di dalam rumah malah mirip tangki penuh — sehingga diagnosis ganda wajib dilakukan sebelum membeli jasa apa pun.",
"<h2>Pastikan Dulu: Resapan atau Tangki?</h2>",
"Tangki penuh: aliran dari kloset lambat, bau di area bak kontrol, genangan dekat jalur inlet. Resapan jenuh: kloset kadang normal, tapi area resapan (biasaan ditutup paving/rumput) selalu becek, bau muncul di sisi keluar, dan kondisi memburuk setelah hujan. Banyak rumah mengalami keduanya sekaligus — maka urutannya selalu: kosongkan tangki dulu, beri masa uji 1–2 minggu, baru nilai daya serap resapan tanpa gangguan beban berlebih.",
"Tes cepat: siram 2 ember air ke tutup inspeksi resapan (bukan kloset). Amati permukaan air di dalam sumur resapan — kalau turun kurang dari 15–20 menit per sentimeter, daya serap masih layak; kalau nyaris stagnan berjam-jam, biomat sudah menebal.",
"<h2>Tingkat 1: Istirahatkan dan Sanggah</h2>",
"Untuk resapan yang baru menurun, kurangi beban 1–2 minggu: alihkan air cucian ke jalur lain, jangan siram berlebihan, dan biarkan pori tanah \"bernafas\" — biomat adalah lapisan mikroba yang menebal saat kejenuhan dan menyusut perlahan saat diberi waktu kering. Kombinasikan dengan penyedotan tangki agar inlet resapan tidak menerima cairan bermuatan lumpur halus.",
"@@                <div class=\"info-box\">\n                    <strong>Jangan lakukan</strong>\n                    Menuang soda api/pelarut ke sumur resapan \"untuk menembus\". Ia membunuh biomat DAN bakteri tangki, merusak struktur tanah liat sekitarnya, dan polutan masuk ke air tanah. Tidak ada bahan kimia yang mengembalikan daya serap yang hilang oleh kompaksi.\n                </div>",
"<h2>Tingkat 2: Bongkar Isian, Ganti Media</h2>",
"Kalau istirahat tidak menolong, isian lama (bata, kerikil, ijuk) sudah tersaturasi lemak dan lumpur halus. Buka sumur/bidang resapan, keluarkan isian, kerik bagian dinding tanah dengan sekop untuk mengangkat lapisan licin biomat, isi ulang dengan batu belah bersih + ijuk + cocoper sebagai filter bertingkat. Pekerjaan satu-dua hari ini sering memulihkan daya serap 60–80% tanpa konstruksi baru.",
"Untuk bidang resapan datar di bawah paving, alternatifnya membuat sumur resapan vertikal baru berdampingan dengan pipa penghubung — cara legal-modern yang hemat lahan kampung: diameter 0,8–1 m, kedalaman 2–3 m, dinding berpori dengan geotekstil.",
"<h2>Tingkat 3: Resapan Baru dan Aturan Jarak</h2>",
"Kalau tanah murni lempung padat atau muka air tinggi, resapan konvensional memang tidak akan pernah pulih permanen. Jalannya: sumur resapan dalam menembus lapisan porous, atau — pilihan terbaik untuk kawasan padat — mengalirkan efluen ke parit infiltrasi panjang yang dibagi-bagi bebannya. Jaga jarak minimal 5 m dari sumur air bersih dan 1,5 m dari pondasi; dokumen IPL/PDAM setempat mengatur angka detail untuk kota Anda.",
"Perencanaan resapan baru sebaiknya dikerjakan bersamaan dengan sedot terjadwal: satu crew memahami kondisi volume tangki Anda, jarak jalur, dan kualitas tanah dari laporan lapangan — data yang sama dipakai untuk menentukan tipe resapan yang realistis, bukan spekulatif.",
"<h2>Rutinitas Pencegahan Musiman</h2>",
"Sebelum November: kosongkan tangki sesuai jadwal, potong akar dekat jalur resapan, bersihkan tutup sumur dari tanah penutup. Selama puncak hujan: alihkan air atap agar tidak membanjiri area resapan. Setelah musim: lakukan tes 2 ember di atas. Tiga ritual kecil ini membedakan rumah yang bertahan lintas musim hujan dan rumah yang tiap tahun memanggil truk.",
], [
("Berapa lama resapan pulih setelah diistirahatkan?", "Biasanya 1–3 minggu untuk saturasi ringan. Kalau setelah 3 minggu tes ember tetap stagnan, lanjut tingkat 2 (ganti media) — menunggu lebih lama tidak memperbaiki kompaksi."),
("Tanah timbunan baru cocok untuk resapan?", "Timbunan padat justru musuh infiltrasi. Beri waktu settle 6 bulan atau buat sumur dalam menembus lapisan asli; jangan memaksakan bidang resapan dangkal di tanah urug."),
("Bolehkah resapan digabung dengan septic tank jadi satu unit?", "Ada model combined (tangki + kompartemen resapan) untuk lahan sempit, tapi perawatannya lebih ketat dan umurnya lebih pendek. Konsultasikan desain dengan kondisi tanah setempat sebelum memilih."),
("Paving di atas resapan menghalangi pemulihan?", "Tidak selalu — paving berpori atau celah sambungan masih memberi ventilasi. Yang fatal adalah cor plester rapat tanpa celah: tanah tidak bisa menguap dan biomat tidak menyusut. Bobok sebagian bila perlu."),
])

build("sedot-wc-kos-kontrakan", 4, [
"<strong>Saat WC kos mampet, aturan praktisnya begini: kerusakan akibat pemakaian sehari-hari adalah tanggung jawab pemilik properti, sedangkan kerusakan akibat kelalaian penghuni (membuang sampah padat ke kloset) dapat dibebankan kepada yang bersangkutan.</strong> Karena itu langkah pertama penghuni bukan mencari tukang, melainkan melapor cepat dan terdokumentasi ke pemilik/keluarga pengelola — sebelum keadaan bertambah parah dan biayanya membesar.",
"Kamar mandi bersama puluhan pengguna punya pola kerusakan khas: tisu menumpuk, hair catch shower jarang dibersihkan, dan tangki yang dihitung untuk 6 orang dipakai 15 orang. Panduan ini berlaku untuk anak kos, ibu kos, dan pemilik kontrakan di Medan — siapa menghubungi siapa, apa yang wajib disiapkan, dan bagaimana membagi biaya secara adil tanpa drama.",
"<h2>Untuk Penghuni: Protokol Laporan Cepat</h2>",
"Langkah Anda saat menemukan mampet: (1) berhenti menggunakan kamar mandi tersebut, tempel kertas \"JANGAN DIPAKAI\"; (2) foto/video gejala — air setinggi apa, ada genangan di mana; (3) kirim ke grup penghuni + pemilik dengan kalimat jelas: \"Kloset kamar 4 lambat sejak semalam, wastafel normal\"; (4) jangan coba-coba menuang bahan kimia sendiri — biaya perbaikan akibat soda api bisa berbalik tagihan ke Anda.",
"Laporkan secepatnya bahkan untuk gejala ringan. Di bangunan multi-penghuni, \"nanti juga lancar\" berubah jadi luapan koridor dalam 48 jam. Penghuni yang melapor cepat hampir selalu dipandang positif; yang menutupi sampai meluber, sebaliknya.",
"<h2>Untuk Ibu Kos: Diagnosis Mandiri 10 Menit</h2>",
"Sebelum menelepon jasa, tentukan jenis masalah: satu kloset lambat saja = sumbatan lokal, coba plunger (sediakan satu plunger berkualitas di gudang — investasi wajib kos). Semua titik lambat + bau di got belakang = tangki/resapan, jadwalkan sedot. Wastafel/shower lambat = rambut dan sabun, bersihkan trap. Catat tanggal sedot terakhir di buku khusus; kalau sudah lewat interval, panggilan darurat Anda sebenarnya jadwal rutin yang tertunda.",
"@@                <div class=\"info-box\">\n                    <strong>Aturan pembagian biaya yang adil</strong>\n                    Tangki &gt; interval jadwal → biaya pemilik (pemeliharaan). Sumbatan oleh benda asing terbukti (mainan, pembalut, hp) → penghuni terkait. Kerusakan karena bangunan (kemiringan pipa, tangki bocor) → pemilik. Tulis kesepakatannya di kontrak sewa sejak awal — klausul \"rusak karena pemakaian vs kelalaian\" mencegah 90% pertengkaran.\n                </div>",
"<h2>Untuk Pemilik: Desain Anti-Drama</h2>",
"Kos >10 kamar sebaiknya tidak berbagi satu tangki kecil. Opsi teknis: tangki modular 3.000 liter, dua compartment paralel per blok kamar mandi, atau kontrak sedot terjadwal 6 bulanan dengan harga paket — biaya predictable, reputasi terjaga, penyewa betah. Tambah satu kebiasaan murah: tempel instruksi \"buang tisu di tempat sampah\" di setiap pintu kamar mandi; efektivitasnya melawan kebiasaan lebih tinggi dari brosur manapun.",
"Inspeksi triwulan 5 menit: buka bak kontrol, lihat warna dan ketinggian, cek bau halaman. Sepuluh menit per kuartal mencegah kejadian \"kos bau\", faktor nomor satu calon penyewa kabur sebelum deal.",
"<h2>Skema Biaya yang Adil dan Transparan</h2>",
"Untuk pekerjaan darurat, minta rincian tertulis via WhatsApp sebelum teknisi berangkat: lingkup (sedot vs dongkrak), estimasi rit, dan akses gang. Penghuni boleh patungan operasional ringan (misal biaya material pembersih), tetapi komponen modal (truk sedot, penggantian pipa) tetap domain pemilik — kecuali kelalaian terbukti. Semua pihak tenang ketika garisnya jelas.",
"Dan untuk keluhan berulang di kos lama: kadang akar masalahnya kemiringan pipa atau tangki under-capacity warisan pembangunan. Sekali biaya audit menyeluruh bisa menghapus langganan sedot darurat tahunan — hitung sebagai investasi kenyamanan penyewa, bukan pengeluaran hangus.",
], [
("Pemilik menolak bertanggung jawab, harus bagaimana?", "Rujuk perjanjian sewa tertulis; jika tidak ada, mediasi RT/kelurahan. Dokumentasi laporan cepat + foto sangat menentukan posisi tawar penghuni."),
("Berapa interval sedot untuk kos 12 kamar?", "Tangki standar 1.500–2.000 L: rata-rata 6–9 bulan. Pantau volume terangkat kunjungan pertama, lalu kalibrasi jadwal dari angka nyata itu."),
("Anak kos sering membuang popok/sanitasi — bagaimana menegurnya?", "Sediakan tempat sampah bertutup + kantong kecil di tiap kamar mandi; ubah larangan menjadi fasilitas. Teguran lisan tanpa alternatif jarang berhasil."),
("Bisa minta invoice atas nama pemilik untuk klaim biaya perusahaan kos?", "Ya, sebutkan saat penjadwalan; kwitansi/rincian resmi diterbitkan sesuai nama penanggung jawab pembayaran."),
])
