#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch 3 (Fase 4 lanjutan): artikel 11-15."""
from gen_articles import build

build("sedot-wc-usaha-restoran", 5, [
"<strong>Restoran di Medan punya dua masalah limbah yang tidak dimiliki rumah tangga: lemak dapur yang membeku di pipa dan volume sampah organik yang membebani tangki.</strong> Kombinasi keduanya membuat septic tank restoran penuh 2–4 kali lebih cepat daripada rumah dengan luas sama. Solusinya bukan sekadar sedot lebih sering, tapi memasang interceptor grease (perangkap lemak) dan menjadwalkan penyedotan berdasarkan pengukuran, bukan tebakan.",
"Satu insiden luber di jam makan siang bisa menghentikan operasional dan mencoreng reputasi. Artikel ini membahas desain alur limbah restoran kecil sampai menengah, ukuran interceptor yang wajar, dan SOP kebersihan dapur yang menjaga sistem tetap awet antar-kunjungan teknisi.",
"<h2>Kenapa Lemak Adalah Musuh Utama</h2>",
"Lemak cair saat wajan panas, lalu membeku di pipa yang lebih dingin membentuk kerak yang lama-kelamaan menyempit sampai tersumbat total (fatberg). Kalau sumbatan terjadi sebelum tangki, air cucian piring menggenang di floor drain dapur — bau, kumuh, dan rawan disoal dinas kesehatan. Interceptor grease bertugas menahan lemak SEBELUM masuk tangki; tanpa itu, seluruh lemak berakhir sebagai scum tebal yang menyedot kapasitas penguraian Anda.",
"@@                <div class=\"info-box\">\n                    <strong>Aturan ukuran interceptor</strong>\n                    Dapur dengan kurang dari 3 meja cuci: 60–90 L. Dapur wok tinggi / 100+ kursi: 120–250 L atau dua unit paralel. Yang menentukan bukan luas restoran, tapi jumlah liter air bilas per jam puncak. Interceptor terlalu kecil = sama saja tidak pasang.\n                </div>",
"<h2>Jadwal Sedot Realistis untuk Restoran</h2>",
"Rumah tangga: 3–5 tahun. Restoran 50 kursi dengan interceptor terawat: 12–18 bulan. Tanpa interceptor: bisa tiap 4–6 bulan dan pipa ikut menjerit. Cara kalibrasi paling jujur: catat volume terangkat pada penyedotan pertama, bandingkan dengan kapasitas tangki, hitung kecepatan pengisian harian dari angka itu. Dari data nyata tersebut jadwal tahunan Anda berhenti jadi tebakan dan mulai jadi anggaran.",
"<h2>SOP Harian yang Menyelamatkan Tangki</h2>",
"Tiga kebiasaan murah dengan dampak besar: (1) scrape dulu, baru wash — sisa makanan dibuang ke tempat organik sebelum piring masuk air; (2) jangan buang minyak jelantah ke saluran mana pun, tampung dan serahkan ke pengumpul; (3) kuras interceptor tiap minggu (bukan tiap bulan) — lemak yang dibiarkan 30 hari mulai terurai anaerob dan menghasilkan bau sulfida yang menyerupai got, keluhan klasik pelanggan depan. Training satu kalimat untuk kru: \"yang tidak larut, tidak masuk saluran.\"",
"<h2>Kapan Panggil Teknisi Sebelum Masuk Jam Buka</h2>",
"Gejala pra-bencana: bilas wastafel dapur melambat 2–3 hari berturut-turut, suara glubuk dari floor drain, atau bau meningkat saat blower hood mati malam hari. Jangan tunggu luber. Booking pagi buta atau setelah tutup adalah slot favorit kami untuk klien F&B karena pekerjaan jetting berisik dan becek — diselesaikan diam-diam, restoran buka normal, pelanggan tidak pernah tahu ada truk tangki di gang belakang.",
], [
("Interceptor wajib untuk izin usaha?", "Untuk IMB/PBG dan dokumen lingkungan tertentu, instalasi pengolahan limbah domestik (termasuk perangkap lemak) diperiksa. Kota/kabupaten punya perda berbeda; konsultasikan dengan dinas terkait setempat sebelum renovasi dapur."),
("Berapa biaya kuras interceptor sendiri?", "Nol rupiah selain kantong plastik dan sarung tangan — 15 menit tiap minggu. Biaya sesungguhnya muncul kalau Anda skip: sedot darurat + jetting pipa bisa 5–10 kali lipat."),
("Enzyme pemecah lemak boleh dipakai?", "Boleh sebagai pelengkap, bukan pengganti skimming manual. Enzim butuh waktu tinggal (retention time) panjang; di dapur yang airnya mengalir terus, sebagian besar enzim lewat begitu saja."),
("Sudah pakai grease trap besar, masih perlu sedot WC berkala?", "Ya. Grease trap melindungi jalur, tapi lumpur padat tetap menumpuk di tangki septik. Dua-duanya dijadwalkan terpisah."),
])

build("prosedur-teknisi-sedot-wc", 5, [
"<strong>Prosedur standar teknisi sedot WC profesional terdiri dari tujuh langkah: survei singkat, proteksi area, pembukaan akses, penyedotan bertahap, pemecahan gumpalan, verifikasi volume, dan penutupan rapi.</strong> Mengetahui urutan ini membantu Anda menilai kualitas layanan sebelum dan sesudah kerja — teknisi yang melompati langkah proteksi atau tidak memberi bukti volume biasanya tim yang sama yang akan meninggalkan bau besok pagi.",
"Banyak pemilik rumah ragu memanggil jasa karena pengalaman buruk: selang bocor, lantai kotor, biaya mendadak membengkak. Semua itu gejala prosedur yang tidak jalan. Artikel ini membuka isi SOP kami apa adanya, plus tiga pertanyaan yang sebaiknya Anda ajukan saat booking.",
"<h2>Langkah 1–3: Survei, Proteksi, Akses</h2>",
"Survei 3–5 menit: lokasi bak kontrol, jarak truk ke tangki, akses listrik, dan riwayat terakhir disedot. Proteksi: alas karpet di jalur bawa alat, semprot disinfektan ringan di area tutup, sarung tangan dan sepatu bot bersih. Pembukaan akses: tutup beton diangkat dengan alat ungkit khusus — bukan linggis liar yang memecahkan lidah tutup. Kalau tutup lama sudah retak, teknisi jujur akan mencatat dan menyarankan penggantian, bukan pura-pura tidak lihat.",
"<h2>Langkah 4–5: Penyedotan dan Pemecahan Gumpalan</h2>",
"Selang hisap berdiameter besar (umumnya 4 inci) dimasukkan ke chamber pertama. Pompa vakum menarik lapisan scum atas lebih dulu, lalu lumpur tengah, lalu endapan dasar. Gumpalan padat yang menyumbat selang dipecah dengan water jet tekanan balik dari dalam tangki — bukan dengan mendorong kayu. Prinsip kerjanya: material keluar dalam bentuk slurri homogen; kalau masih banyak benda utuh berarti hisapan belum tuntas.",
"@@                <div class=\"info-box warn\">\n                    <strong>Tanda merah di lapangan</strong>\n                    Selang menetes di atas jalan tanpa wadah penampung tetesan, teknisi menolak menunjukkan volume terangkat, atau tiba-tiba ada \\\"biaya tambahan bahan kimia\\\" setelah pekerjaan selesai. Tinggalkan dan cari operator lain — SOP yang benar selalu bisa dijelaskan dengan tenang.\n                </div>",
"<h2>Langkah 6–7: Verifikasi dan Penutupan</h2>",
"Verifikasi: volume terangkat dilaporkan (mis. 1.800 L dari tangki 2.000 L), bilasan akhir dites — air baru yang diguyurkan harus surut cepat tanpa gelekan balik. Penutupan: tutup dipasang rapat (kunci anti-geser bila tersedia), area dibilas, karpet jalur digulung, dan foto dokumentasi dikirim ke kontak WA bila diminta. Nota digital dikirim hari yang sama; kwitansi resmi atas nama perusahaan tersedia untuk klien kantor/badan usaha.",
"<h2>Tiga Pertanyaan Saat Booking</h2>",
"(1) Berapa estimasi durasi dan apakah harga sudah termasuk jetting selang? (2) Apakah volume terangkat dilaporkan tertulis? (3) Bagaimana penanganan bila ditemukan retak pada tutup atau pipa? Jawaban yang lugas dan spesifik menandakan operator yang bekerja dengan SOP; jawaban ngawur adalah filter gratis Anda sebelum mobil tangki berangkat.",
], [
("Berapa lama rata-rata pengerjaan rumah tangga?", "45–90 menit termasuk proteksi dan pembersihan, tergantung jarak selang dan kadar lumpur. Tangki yang jarang disedot (lebih dari 5 tahun) bisa lebih lama karena endapan memadat."),
("Apakah harus mengosongkan kamar mandi?", "Tidak. Cukup hindari pemakaian kloset selama proses agar level air stabil. Pengerjaan tetap aman dengan penghuni di rumah."),
("Kapan waktu terbaik menjadwalkan?", "Pagi hari untuk area perumahan padat; setelah tutup untuk ruko/restoran. Hindari jam hujan lebat bila bak kontrol berada di halaman terbuka."),
("Kenapa bau masih ada setelah disedot?", "Biasanya karena resapan jenuh, bukan tangki. Setelah hisap, cek surutnya air bilas; kalau lambat, pembahasan berlanjut ke sisi hilir (resapan/drainase)."),
])

build("pilihan-material-septic-tank", 5, [
"<strong>Tiga material septic tank yang umum di Medan — beton cast-in-place, panel beton pracetak, dan fiberglass/HDPE — masing-masing unggul di kondisi berbeda: tanah keras kering cocok beton, lahan sempit basah cocok pracetak, akses sempit dan muka air tinggi cocok fiberglass.</strong> Tidak ada material \"terbaik secara mutlak\"; yang ada adalah pasangan material-kondisi-lahan yang tepat untuk rumah Anda.",
"Pilihan material menentukan umur pakai, risiko rembesan, dan biaya gali. Kesalahan mahal yang sering terjadi: memilih fiberglass karena murah, padahal pemasangannya tanpa ballast di lahan bermuka air tinggi sehingga tangki \"mengambang\" dan jalur pipa patah. Artikel ini membandingkan ketiganya secara teknis dengan bahasa yang bisa Anda pakai saat berbicara dengan kontraktor.",
"<h2>Beton Cor di Tempat: Kuat tapi Sensitif</h2>",
"Kelebihan: rigid, umur 20+ tahun, mudah diperbesar volumenya, material tersedia di toko bangunan mana pun di Medan. Kekurangan: sangat bergantung pada mutu adukan dan perawatan curing; campuran asal-asalan retak rambut dalam 2–3 musim, dan retak berarti rembes serta mencemari air tanah. Waktu pasang paling lama (7–14 hari termasuk curing). Cocok untuk rumah baru dengan lahan lega dan pengawas proyek yang paham.",
"<h2>Panel Pracetak: Jalan Tengah Populer</h2>",
"Dibawa per panel, dirakit di lubang dengan sambungan mortir/adhesive waterproof. Pasang 2–4 hari, kekuatan konsisten karena dicetak pabrik. Kelemahan ada di titik sambungan: kualitas kedap ditentukan kerapatan nat antar-panel — minta uji rendam (isi penuh, tandai level, biarkan 24 jam) sebelum urug kembali. Ini tes 5 menit yang menyelamatkan Anda dari galian ulang setahun kemudian.",
"<h2>Fiberglass/HDPE: Cepat, Ringan, Butuh Ballast</h2>",
"Satu unit bulat/elips, hanya perlu crane manual/tali dan galiannya paling kecil — juara untuk gang sempit Sunggal/Denai yang mobil barang tidak bisa masuk. Kedap sempurna terhadap gas dan air. Tapi bobot ringan menjadi kutukan di lahan berair: wajib dipasang di atas lantai kerja beton dengan angkur ballast bila muka air tanah tinggi, dan diurug pasir (bukan puing tajam). Riwayat kegagalan fiberglass hampir selalu soal pemasangan, bukan produknya.",
"@@                <div class=\"info-box\">\n                    <strong>Ringkas biaya relatif (unit setara 1.500–2.000 L, terpasang)</strong>\n                    Beton cor: material murah, tenaga dan waktu mahal. Pracetak: seimbang. Fiberglass: unit Rp1,5–3 juta tergantung merek, gali murah, ballast menambah sedikit. Angka kasar berubah tiap musim — minta penawaran tertulis terperinci dari dua vendor untuk pembanding.\n                </div>",
"<h2>Indikator Kualitas yang Sering Dilupakan: Baffle</h2>",
"Apapun materialnya, pastikan ada inlet-outlet baffle (sekat T) yang mencegah scum keluar ke resapan. Tangki mahal tanpa baffle kalah dari tangki murah dengan baffle rapi. Dan beri ventilasi minimal diameter 75 mm di chamber kedua — gas metana yang terperangkap adalah penyebab tutup melenting dan bau di sekitar bak kontrol yang sering dikira \"tangki bocor\".",
], [
("Umur pakai tiap material?", "Beton cor bermutu: 20–30 tahun. Pracetak: 15–25 tahun. Fiberglass berkualitas: 10–20 tahun (sambungan dan ballast menentukan). Semua bisa jauh lebih pendek jika instalasi asal-asalan."),
("Bagaimana mengecek material tangki lama saya?", "Buka bak kontrol: permukaan kasar berpori berarti beton; serat anyaman mengilap berarti fiberglass; nat antar-lempeng berarti panel pracetak. Foto dinding dalamnya, kirim ke teknisi untuk konfirmasi."),
("Boleh ganti fiberglass di atas pondasi beton lama?", "Boleh, dengan syarat dasar lubang rata dan diberi lantai kerja baru sesuai spesifikasi ballast pabrikan. Jangan menempatkan badan ringan langsung di atas rongga bekas."),
("Mana yang tahan pergerakan tanah gambut?", "Unit monolitik (fiberglass/beton cetak pabrik) lebih toleran terhadap pergerakan tanah daripada struktur bersambungan banyak. Untuk lahan gambut, perkuat dengan angkur dan backfill pasir seragam."),
])

build("gejala-septic-tank-masih-baik", 4, [
"<strong>Septic tank yang sehat ditandai empat hal sederhana: air bilas surut cepat tanpa gelembung balik, tidak ada bau di sekitar bak kontrol dan halaman, permukaan air di chamber hanya sampai batas pipa outlet, dan tidak ada genangan abnormal di area resapan setelah pemakaian berat.</strong> Selama empat tanda itu terpenuhi, jadwal sedot normal tetap berjalan dan Anda tidak perlu memanggil siapa pun.",
"Membaca \"kepribadian\" tangki sendiri adalah keterampilan berbiaya rendah bernilai tinggi: sekali paham, Anda bisa membedakan antara kewaspadaan berlebihan dan masalah nyata yang butuh teknisi. Artikel ini menyusun checklist dua menit yang bisa dilakukan siapa saja, plus frekuensi pemeriksaan yang wajar.",
"<h2>Checklist Dua Menit Tiap Tiga Bulan</h2>",
"Satu: siram kloset dua kali berturut-turut — surut harus konsisten, tanpa naiknya air di shower terdekat. Dua: intip bak kontrol (pakai sarung tangan, jangan condongkan wajah) — level cairan idealnya setinggi pipa outlet, bukan menutupi tutup. Tiga: cium radius dua meter dari bak kontrol dan jalur resapan. Empat: injak-injak lembut tanah di area resapan setelah 100+ liter air dipakai (mencuci dan mandi) — harus padat-normal, bukan seperti spons basah berbau.",
"<h2>Tanda Normal yang Sering Disalahartikan</h2>",
"Bau samar beberapa jam setelah disedot: normal, sisa paparan udara terbuka. Geledek pelan di pipa saat disiram: umumnya udara venting biasa. Rumput di atas resapan sedikit lebih hijau: bisa jadi nutrisi dari rembesan halus — pantau, belum tentu gagal. Yang TIDAK normal: gelembung balik di kloset, genangan persisten, dan bau sulfida permanen di dekat tutup.",
"@@                <div class=\"info-box\">\n                    <strong>Catatan kecil yang berguna besar</strong>\n                    Buat log satu baris per kuartal di HP: tanggal, hasil 4 poin checklist, dan volume terangkat pada sedot terakhir. Setelah dua siklus, Anda punya kurva pengisian nyata milik rumah sendiri — dasar kuat untuk menegosiasikan jadwal preventif, bukan reaktif.\n                </div>",
"<h2>Ambang Batas: Kapan Checklist Berubah Jadi Telepon</h2>",
"Jika dua dari empat tanda merah muncul bersamaan, atau satu tanda menetap lebih dari seminggu, hentikan diagnosis mandiri. Itu wilayah alat: volume sludge perlu diukur dengan spit-and-sample atau sensor, dan resapan perlu uji laju serap. Memanggil teknisi pada tahap ini adalah panggilan preventif (murah, bersih, cepat) — menunggu luber mengubahnya jadi pekerjaan darurat yang lebih mahal dan jauh lebih kotor.",
], [
("Haruskah mengecek tangki saat musim kemarau juga?", "Ya. Kemarau justru saat resapan paling mudah diuji laju serapnya; temuan jelek di kemarau adalah bom waktu saat hujan datang."),
("Air bilas kadang lambat, kadang normal — bahaya?", "Pola intermiten biasanya awal penyumbatan parsial di sifon/jalur, atau level tangki sudah mendekati ambang. Cek dua siklus berikutnya; kalau menetap, jadwalkan kunjungan."),
("Muncul bau setelah hujan deras, padahal tangki baru disedot bulan lalu?", "Kemungkinan besar resapan jenuh air hujan, bukan tangki. Aliran permukaan halaman perlu ditata ulang agar tidak mencuci area resapan."),
("Anak suka main dekat bak kontrol, aman?", "Tidak. Tutup lama sering tidak terkunci dan beban anak cukup untuk membuka celah berbahaya. Ajarkan zona terlarang dan pertimbangkan tutup dengan kunci anak."),
])

build("musim-hujan-dan-septic-tank", 4, [
"<strong>Musim hujan memperburuk masalah septic tank melalui dua mekanisme: muka air tanah naik sehingga daya serap resapan runtuh, dan limpasan air hujan yang masuk ke bak kontrol lewat tutup bocor membanjiri sistem dengan volume berlebih.</strong> Karena itu keluhan sedot WC di Medan memuncak November–Januari: tangki yang di kemarau terasa aman, di musim hujan mendadak penuh dan berbau.",
"Kabar baiknya, separuh dari banjir musiman ini bisa dicegah dengan pekerjaan kecil menjelang hujan: membenahi drainase halaman, merapatkan tutup, dan memajukan jadwal sedot satu tingkat. Panduan ini disusun mengikuti pola iklim Sumatera Utara — hujan puncak akhir tahun, transisi kering Maret–Mei sebagai jendela perawatan terbaik.",
"<h2>Kenapa Sistem Terasa Lebih Penuh Saat Hujan</h2>",
"Tangki tidak bertambah isi karena langit; yang berubah adalah hilirnya. Resapan dikelilingi pori tanah yang sudah jenuh air hujan sehingga output tangki nyaris berhenti mengalir keluar. Level naik, bilasan melambat, dan gas mencari jalan lain lewat kloset. Ditambah lagi talang yang bocor atau halaman miring ke arah bak kontrol mengirim puluhan liter per hujan deras langsung ke sistem yang seharusnya hanya menerima limbah domestik.",
"<h2>Pekerjaan Persiapan Oktober (Sebelum Puncak)</h2>",
"Empat tindakan, semuanya di bawah setengah hari kerja: rapatkan tutup bak kontrol dengan seal semen/packing; arahkan ulang drainase halaman supaya keluar ke got kota, bukan ke area resapan; bersihkan ujung ventilasi atap dari sarang laba-laba dan daun; dan jika siklus sedot Anda jatuh di Desember–Januari, majukan ke Oktober–November supaya kunjungan terjadi dalam kondisi kering — lebih bersih, lebih murah, tanpa antrean puncak.",
"@@                <div class=\"info-box warn\">\n                    <strong>Jangan lakukan ini saat genangan</strong>\n                    Menyiram kloset berulang untuk \\\"memancing\\\" surut hanya menambah volume ke sistem yang sedang jenuh. Membuka paksa tutup di halaman tergenang juga berbahaya: gas metana plus percikan adalah kombinasi buruk, dan Anda mengotori air limpasan yang mengalir ke selokan warga.\n                </div>",
"<h2>Setelah Hujan: Evaluasi Lima Menit</h2>",
"Beberapa hari setelah hujan panjang berhenti, lakukan jalan kaki inspeksi: apakah tanah di sekitar resapan masih lunak berbau setelah 3–4 hari cerah? Apakah level bak kontrol turun ke garis normal? Dua-duanya ya — sistem Anda lulus ujian musim ini. Salah satunya menetap — itu sinyal resapan perlu perlakuan (pengeringan paksa, kuras, atau rehabilitasi media), dan waktunya sekarang, bukan hujan berikutnya.",
], [
("Wajar tagihan sedot naik saat musim hujan?", "Permintaan memang melonjak, tapi operator kredibel mengumumkan tarif tetap sejak awal. Minta rincian sejak booking; perubahan harga sesaat di lapangan adalah red flag."),
("Resapan jenuh setiap musim hujan, solusi jangka panjangnya?", "Perluas bidang resapan sesuai perhitungan debit, atau pasang sumur injeksi air hujan terpisah agar limpasan tidak membebani sistem septik. Rehabilitasi media (buang lapisan biomat teratas, isi kerikil baru) adalah opsi tengah yang hemat."),
("Bolehkah pompa celup dipakai untuk mempercepat surut?", "Untuk menguras genangan halaman, ya. Untuk menyedot isi tangki, tidak — Anda hanya memindahkan scum dan merusak keseimbangan bakteri. Serahkan isi tangki pada vakum profesional."),
("Kapan musim terbaik merehabilitasi resapan?", "Juli–September: tanah kering, akses alat mudah, dan Anda selesai sebelum ujian hujan berikutnya datang."),
])
